baseURL: "https://nicoan.github.io/"
# title: Sur v ¬Sur
paginate: 8
theme: papermod
enableInlineShortcodes: true
enableRobotsTXT: true

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            # main:
                # - name: About me
                #   url: about
                #   weight: 5
                # - name: Blog
                #   url: blog/
                #   weight: 10

    # es:
    #     languageName: "Español"
    #     weight: 2
    #     menu:
            # main:
                # - name: Sobre mi
                #   url: about
                #   weight: 5
                # - name: Blog
                #   url: blog/
                #   weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "My personal site"
    author: Nicolás Antinori
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    profileMode:
          enabled: true
          title: Nicolás Antinori
          subtitle: Fullstack developer
          imageUrl: "/images/profile.jpeg"
          imageTitle: Me


    socialIcons:
        - name: github
          url: "https://github.com/nicoan"
        - name: linkedin
          url: "https://www.linkedin.com/in/nicolas-antinori"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

